### ISSUE TITLE
MemPriority实现错误

### ISSUE THREAD

**Issue by vilinian** [SilenceSu/behavior3java#1]
https://github.com/SilenceSu/behavior3java/blob/fc6e8b2a94c6cb2787b4d9b0dd544b59c2a69337/src/main/java/com/susu/b3/composites/MemPriority.java#L27-L38

这一行是不是写错了，应该放到  if (status != B3Status.FAILURE) {  这个if里面吧
@SilenceSu

**Comment by SilenceSu** [comment]
感谢指正，这一款是因该在if里面 return
